<?php
/**
 * DatabaseFormat
 *
 * PHP version 8.1
 *
 * @package  InternetData\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * InternetData API
 *
 * The InternetData API: download the databases your organization is licensed for, and manage the account behind them.  See https://docs.internetdata.io for guides and https://github.com/internetdata for the official client libraries.
 *
 * The version of the OpenAPI document: 2026.09.21
 * Contact: support@internetdata.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace InternetData\Internal\Model;

/**
 * DatabaseFormat Class Doc Comment
 *
 * @description A file format a database version is published in.
 * @package  InternetData\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum DatabaseFormat: string
{
    case CSVGZ = 'csvgz';

    case MMDB = 'mmdb';
}


