<?php
/**
 * DatabaseDownload400Response
 *
 * PHP version 8.1
 *
 * @package  InternetData\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * InternetData API
 *
 * The InternetData API. Please see https://docs.internetdata.io/api for more details.
 *
 * The version of the OpenAPI document: 2026.09.04
 * Contact: dev@internetdata.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace InternetData\Internal\Model;

/**
 * DatabaseDownload400Response Class Doc Comment
 *
 * @package  InternetData\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DatabaseDownload400Response implements OneOfInterface
{
    /**
     * The original name of the model.
     *
     * @var string
     */
    public const MODEL_NAME = 'databaseDownload_400_response';

    /**
     * The discriminator property name, or null when the schema has no discriminator.
     *
     * @var string|null
     */
    public const DISCRIMINATOR = null;

    /**
     * {@inheritdoc}
     */
    public static function getOneOfTypes(): array
    {
        return [
            '\InternetData\Internal\Model\DbInvalidFormatError',
            '\InternetData\Internal\Model\DbInvalidIdError'
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function getOneOfDiscriminator(): ?string
    {
        return self::DISCRIMINATOR;
    }

    /**
     * {@inheritdoc}
     */
    public static function getOneOfDiscriminatorMappings(): array
    {
        return [
            
        ];
    }
}


