<?php
/**
 * Standing
 *
 * PHP version 8.1
 *
 * @package  InternetData\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * InternetData API
 *
 * The InternetData API. Please see https://docs.internetdata.io/api for more details.
 *
 * The version of the OpenAPI document: 2026.09.13
 * Contact: dev@internetdata.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace InternetData\Internal\Model;

/**
 * Standing Class Doc Comment
 *
 * @description Where your licence for a database family stands today. &#x60;licensed&#x60; is a live grant, &#x60;expired&#x60; one whose term has ended, and &#x60;unlicensed&#x60; a database published but never bought.
 * @package  InternetData\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum Standing: string
{
    case LICENSED = 'licensed';

    case EXPIRED = 'expired';

    case UNLICENSED = 'unlicensed';
}


