<?php
/**
 * DatabaseV2Api
 * PHP version 8.1
 *
 * @package  InternetData\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * InternetData API
 *
 * The InternetData API. Please see https://docs.internetdata.io/api for more details.
 *
 * The version of the OpenAPI document: 2026.09.09
 * Contact: dev@internetdata.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace InternetData\Internal\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use InternetData\Internal\ApiException;
use InternetData\Internal\Configuration;
use InternetData\Internal\HeaderSelector;
use InternetData\Internal\ObjectSerializer;

/**
 * DatabaseV2Api Class Doc Comment
 *
 * @package  InternetData\Internal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DatabaseV2Api
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var array<string,string[]> $contentTypes **/
    public const contentTypes = [
        'databaseChecksumV2' => [
            'application/json',
        ],
        'databaseMetadataV2' => [
            'application/json',
        ],
        'downloadDatabaseV2' => [
            'application/json',
        ],
        'listDatabases' => [
            'application/json',
        ],
        'listDownloads' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation databaseChecksumV2
     *
     * Checksums
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseChecksumV2'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \InternetData\Internal\Model\ChecksumsResponse|\InternetData\Internal\Model\Error
     */
    public function databaseChecksumV2(
        string $id,
        string $format,
        string $contentType = self::contentTypes['databaseChecksumV2'][0]
    ): \InternetData\Internal\Model\ChecksumsResponse|\InternetData\Internal\Model\Error
    {
        list($response) = $this->databaseChecksumV2WithHttpInfo($id, $format, $contentType);
        return $response;
    }

    /**
     * Operation databaseChecksumV2WithHttpInfo
     *
     * Checksums
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseChecksumV2'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \InternetData\Internal\Model\ChecksumsResponse|\InternetData\Internal\Model\Error, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function databaseChecksumV2WithHttpInfo(
        string $id,
        string $format,
        string $contentType = self::contentTypes['databaseChecksumV2'][0]
    ): array
    {
        $request = $this->databaseChecksumV2Request($id, $format, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\ChecksumsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\InternetData\Internal\Model\ChecksumsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\ChecksumsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation databaseChecksumV2Async
     *
     * Checksums
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseChecksumV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function databaseChecksumV2Async(
        string $id,
        string $format,
        string $contentType = self::contentTypes['databaseChecksumV2'][0]
    ): PromiseInterface
    {
        return $this->databaseChecksumV2AsyncWithHttpInfo($id, $format, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation databaseChecksumV2AsyncWithHttpInfo
     *
     * Checksums
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseChecksumV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function databaseChecksumV2AsyncWithHttpInfo(
        string $id,
        string $format,
        string $contentType = self::contentTypes['databaseChecksumV2'][0]
    ): PromiseInterface
    {
        $returnType = '\InternetData\Internal\Model\ChecksumsResponse';
        $request = $this->databaseChecksumV2Request($id, $format, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'databaseChecksumV2'
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseChecksumV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function databaseChecksumV2Request(
        string $id,
        string $format,
        string $contentType = self::contentTypes['databaseChecksumV2'][0]
    ): Request
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling databaseChecksumV2'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_]+$/", $id)) {
            throw new InvalidArgumentException("invalid value for \"id\" when calling DatabaseV2Api.databaseChecksumV2, must conform to the pattern /^[a-zA-Z0-9_]+$/.");
        }
        // verify the required parameter 'format' is set
        if ($format === null || (is_array($format) && count($format) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $format when calling databaseChecksumV2'
            );
        }

        $resourcePath = '/api/v2/database/checksum';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $format,
            'format', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation databaseMetadataV2
     *
     * Metadata
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseMetadataV2'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \InternetData\Internal\Model\DatabaseMetadata|\InternetData\Internal\Model\Error
     */
    public function databaseMetadataV2(
        string $id,
        string $contentType = self::contentTypes['databaseMetadataV2'][0]
    ): \InternetData\Internal\Model\DatabaseMetadata|\InternetData\Internal\Model\Error
    {
        list($response) = $this->databaseMetadataV2WithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation databaseMetadataV2WithHttpInfo
     *
     * Metadata
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseMetadataV2'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \InternetData\Internal\Model\DatabaseMetadata|\InternetData\Internal\Model\Error, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function databaseMetadataV2WithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['databaseMetadataV2'][0]
    ): array
    {
        $request = $this->databaseMetadataV2Request($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\DatabaseMetadata',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\InternetData\Internal\Model\DatabaseMetadata',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\DatabaseMetadata',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation databaseMetadataV2Async
     *
     * Metadata
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseMetadataV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function databaseMetadataV2Async(
        string $id,
        string $contentType = self::contentTypes['databaseMetadataV2'][0]
    ): PromiseInterface
    {
        return $this->databaseMetadataV2AsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation databaseMetadataV2AsyncWithHttpInfo
     *
     * Metadata
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseMetadataV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function databaseMetadataV2AsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['databaseMetadataV2'][0]
    ): PromiseInterface
    {
        $returnType = '\InternetData\Internal\Model\DatabaseMetadata';
        $request = $this->databaseMetadataV2Request($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'databaseMetadataV2'
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['databaseMetadataV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function databaseMetadataV2Request(
        string $id,
        string $contentType = self::contentTypes['databaseMetadataV2'][0]
    ): Request
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling databaseMetadataV2'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_]+$/", $id)) {
            throw new InvalidArgumentException("invalid value for \"id\" when calling DatabaseV2Api.databaseMetadataV2, must conform to the pattern /^[a-zA-Z0-9_]+$/.");
        }

        $resourcePath = '/api/v2/database/metadata';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation downloadDatabaseV2
     *
     * Download
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadDatabaseV2'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \InternetData\Internal\Model\Error
     */
    public function downloadDatabaseV2(
        string $id,
        string $format,
        string $contentType = self::contentTypes['downloadDatabaseV2'][0]
    ): \InternetData\Internal\Model\Error
    {
        list($response) = $this->downloadDatabaseV2WithHttpInfo($id, $format, $contentType);
        return $response;
    }

    /**
     * Operation downloadDatabaseV2WithHttpInfo
     *
     * Download
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadDatabaseV2'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: null, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function downloadDatabaseV2WithHttpInfo(
        string $id,
        string $format,
        string $contentType = self::contentTypes['downloadDatabaseV2'][0]
    ): array
    {
        $request = $this->downloadDatabaseV2Request($id, $format, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation downloadDatabaseV2Async
     *
     * Download
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadDatabaseV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function downloadDatabaseV2Async(
        string $id,
        string $format,
        string $contentType = self::contentTypes['downloadDatabaseV2'][0]
    ): PromiseInterface
    {
        return $this->downloadDatabaseV2AsyncWithHttpInfo($id, $format, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation downloadDatabaseV2AsyncWithHttpInfo
     *
     * Download
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadDatabaseV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function downloadDatabaseV2AsyncWithHttpInfo(
        string $id,
        string $format,
        string $contentType = self::contentTypes['downloadDatabaseV2'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->downloadDatabaseV2Request($id, $format, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'downloadDatabaseV2'
     *
     * @param  string $id Database identifier (e.g. &#x60;vpn_ip_v1&#x60;, &#x60;resproxy_provider_v1&#x60;). (required)
     * @param  string $format Database file format. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadDatabaseV2'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function downloadDatabaseV2Request(
        string $id,
        string $format,
        string $contentType = self::contentTypes['downloadDatabaseV2'][0]
    ): Request
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling downloadDatabaseV2'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_]+$/", $id)) {
            throw new InvalidArgumentException("invalid value for \"id\" when calling DatabaseV2Api.downloadDatabaseV2, must conform to the pattern /^[a-zA-Z0-9_]+$/.");
        }
        // verify the required parameter 'format' is set
        if ($format === null || (is_array($format) && count($format) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $format when calling downloadDatabaseV2'
            );
        }

        $resourcePath = '/api/v2/database/download';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id,
            'id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $format,
            'format', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listDatabases
     *
     * List
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabases'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \InternetData\Internal\Model\DatabaseList|\InternetData\Internal\Model\Error
     */
    public function listDatabases(
        string $contentType = self::contentTypes['listDatabases'][0]
    ): \InternetData\Internal\Model\DatabaseList|\InternetData\Internal\Model\Error
    {
        list($response) = $this->listDatabasesWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation listDatabasesWithHttpInfo
     *
     * List
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabases'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \InternetData\Internal\Model\DatabaseList|\InternetData\Internal\Model\Error, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function listDatabasesWithHttpInfo(
        string $contentType = self::contentTypes['listDatabases'][0]
    ): array
    {
        $request = $this->listDatabasesRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\DatabaseList',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\InternetData\Internal\Model\DatabaseList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\DatabaseList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation listDatabasesAsync
     *
     * List
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabases'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listDatabasesAsync(
        string $contentType = self::contentTypes['listDatabases'][0]
    ): PromiseInterface
    {
        return $this->listDatabasesAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listDatabasesAsyncWithHttpInfo
     *
     * List
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabases'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listDatabasesAsyncWithHttpInfo(
        string $contentType = self::contentTypes['listDatabases'][0]
    ): PromiseInterface
    {
        $returnType = '\InternetData\Internal\Model\DatabaseList';
        $request = $this->listDatabasesRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listDatabases'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDatabases'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listDatabasesRequest(
        string $contentType = self::contentTypes['listDatabases'][0]
    ): Request
    {

        $resourcePath = '/api/v2/database/list';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listDownloads
     *
     * History
     *
     * @param  int|null $limit How many attempts to return. Clamped to 200. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDownloads'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \InternetData\Internal\Model\DownloadList|\InternetData\Internal\Model\Error
     */
    public function listDownloads(
        ?int $limit = 50,
        string $contentType = self::contentTypes['listDownloads'][0]
    ): \InternetData\Internal\Model\DownloadList|\InternetData\Internal\Model\Error
    {
        list($response) = $this->listDownloadsWithHttpInfo($limit, $contentType);
        return $response;
    }

    /**
     * Operation listDownloadsWithHttpInfo
     *
     * History
     *
     * @param  int|null $limit How many attempts to return. Clamped to 200. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDownloads'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \InternetData\Internal\Model\DownloadList|\InternetData\Internal\Model\Error, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function listDownloadsWithHttpInfo(
        ?int $limit = 50,
        string $contentType = self::contentTypes['listDownloads'][0]
    ): array
    {
        $request = $this->listDownloadsRequest($limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\DownloadList',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\InternetData\Internal\Model\Error',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\InternetData\Internal\Model\DownloadList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\DownloadList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\InternetData\Internal\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation listDownloadsAsync
     *
     * History
     *
     * @param  int|null $limit How many attempts to return. Clamped to 200. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDownloads'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listDownloadsAsync(
        ?int $limit = 50,
        string $contentType = self::contentTypes['listDownloads'][0]
    ): PromiseInterface
    {
        return $this->listDownloadsAsyncWithHttpInfo($limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listDownloadsAsyncWithHttpInfo
     *
     * History
     *
     * @param  int|null $limit How many attempts to return. Clamped to 200. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDownloads'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function listDownloadsAsyncWithHttpInfo(
        ?int $limit = 50,
        string $contentType = self::contentTypes['listDownloads'][0]
    ): PromiseInterface
    {
        $returnType = '\InternetData\Internal\Model\DownloadList';
        $request = $this->listDownloadsRequest($limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listDownloads'
     *
     * @param  int|null $limit How many attempts to return. Clamped to 200. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDownloads'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listDownloadsRequest(
        ?int $limit = 50,
        string $contentType = self::contentTypes['listDownloads'][0]
    ): Request
    {
        if ($limit !== null && $limit > 200) {
            throw new InvalidArgumentException('invalid value for "$limit" when calling DatabaseV2Api.listDownloads, must be smaller than or equal to 200.');
        }
        if ($limit !== null && $limit < 1) {
            throw new InvalidArgumentException('invalid value for "$limit" when calling DatabaseV2Api.listDownloads, must be bigger than or equal to 1.');
        }

        $resourcePath = '/api/v2/database/downloads';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
